default_context:
  project_name: 'test'
  project_slug: 'namu'
  domain_main: 'namu.com'
  domain_staging: 'www'
  docker_swarm_stack_name_main: 'namu-com'
  docker_swarm_stack_name_staging: 'www'
  secret_key: 'namu02110'
  first_superuser: 'admin@namu.com'
  first_superuser_password: 'namu02110'
  backend_cors_origins: ' "https://localhost:3000"'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@namu.com'
  postgres_password: 'namu02110'
  pgadmin_default_user: 'admin@namu.com'
  pgadmin_default_user_password: 'namu02110'
  traefik_constraint_tag: 'namu.com'
  traefik_constraint_tag_staging: 'www'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:namu02110'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
